import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import SideBarLeft from '@/components/SideBarLeft'
import Dashboard from '@/components/Dashboard'
import SideBarRight from '@/components/SideBarRight'
import {motion} from 'framer-motion'
import { useState, useEffect} from 'react'
import MenuContext from '@/context/MenuContext';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isOpen , setIsOpen] = useState<boolean>(true);
  const value = {isOpen , setIsOpen}

  useEffect(() => {
    function pageLoad() {
      if(window.innerWidth < 768){
        setIsOpen(false);
      }
    }
    window.addEventListener('load', pageLoad)

    function handleResize() {
      if(window.innerWidth > 768){
        setIsOpen(true);
      }
    }
    window.addEventListener('resize', handleResize)
  }, [])

  return (
    
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <MenuContext.Provider value={value}>
        <SideBarLeft/>
        <Dashboard/>
        <SideBarRight/>
        </MenuContext.Provider>
      </main>
    </>
  )
}
